project:
  type: website

website:
  title: "Aayush Pandey"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: cover-letter.qmd
        text: Cover Letter
      - href: sample-analysis.qmd
        text: Sample Analysis

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    code-fold: show
    code-tools: true

execute:
  warning: false
  message: false